#-----------------------------------------------------------------------------
# Makefile for parallel inplace pcaster
#-----------------------------------------------------------------------------

TARGET = $(BINDIR)/pcaster_remote

TARGET_OBJS = $(PCASTER_REMOTE_OBJS)


include ../make.cfg

DATAFLAGS += -D_PARALLEL
DATAFLAGS += -D_STREAMING
