#-----------------------------------------------------------------------------
# Makefile for parallel inplace pcaster
#-----------------------------------------------------------------------------

TARGET = $(BINDIR)/pcaster_onsite

TARGET_OBJS = $(PCASTER_ONSITE_OBJS)


include ../make.cfg

DATAFLAGS += -D_PARALLEL
#DATAFLAGS += -D_STREAMING
