#-----------------------------------------------------------------------------
# Makefile for viewer
#-----------------------------------------------------------------------------

TARGET = $(BINDIR)/viewer

TARGET_OBJS = $(VIEWER_OBJS)


include ../make.cfg


DATAFLAGS += -D_STREAMING