#-----------------------------------------------------------------------------
# Makefile for standalone renderer
#-----------------------------------------------------------------------------

TARGET = $(BINDIR)/sd_render

TARGET_OBJS = $(SD_RENDER_OBJS)


include ../make.cfg

