#-----------------------------------------------------------------------------
# Makefile for single remote renderer
#-----------------------------------------------------------------------------


TARGET = $(BINDIR)/render 

TARGET_OBJS = $(RENDER_OBJS)


include ../make.cfg


DATAFLAGS += -D_STREAMING